# --- data_analysis.py constants ---
SECONDS_BETWEEN_WARNINGS = 300
# Blink Parameters
BLINK_STARTUP_BUFFER_SECONDS = 30
BLINK_START_THRESHOLD = 0.6
BLINK_END_THRESHOLD = 0.3
BLINK_RATE_LOW_TRIGGER = 15
# PERCLOS Parameters
PERCLOS_THRESHOLD = 0.5
DROWSINESS_THRESHOLD_PERCENTAGE = 15
MIN_CLOSED_SECONDS = 0.5 
MAX_CLOSED_SECONDS = 15
PERCLOS_WINDOW_SECONDS = 60
# Yawn Parameters
JAW_OPEN_THRESHOLD = 0.6
MIN_YAWN_SECONDS = 1.0
MAX_YAWN_SECONDS = 6.0
# Screen Time Parameters
SCREEN_TIME_THRESHOLD_SECONDS = 1200

# --- data_logging.py constants ---
WORKING_DATA_LENGTH = 6000