# --- compliance.py constants ---
PALMING_COMPLIANCE_THRESHOLD = 0.6
PALMING_SECONDS = 30
PALMING_TOLERANCE = 1e-5
TWENTY_COMPLIANCE_THRESHOLD = 0.4
LOOKING_AWAY_THRESHOLD = 0.2
TWENTY_RULE = 20
TWENTY_MINIMUM_ROWS = 2

# --- data_analysis.py constants ---
SECONDS_BETWEEN_WARNINGS = 300
# Blink Parameters
BLINK_STARTUP_BUFFER_SECONDS = 30
BLINK_START_THRESHOLD = 0.6
BLINK_END_THRESHOLD = 0.3
BLINK_RATE_LOW_TRIGGER = 15
# PERCLOS Parameters
PERCLOS_WINDOW_SECONDS = 10
FLOOR_PERCENTAGE = 2
DROWSINESS_THRESHOLD_PERCENTAGE = 15
VERY_DROWSINESS_THRESHOLD_PERCENTAGE = 35
SMOOTH_SIGMA = 5
# Screen Time Parameters
SCREEN_TIME_THRESHOLD_SECONDS = 1200

# --- data_logging.py constants ---
WORKING_DATA_LENGTH = 6000